In [1]:
!pip install requests beautifulsoup4 pandas

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (4.13.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.5.20)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

https://sece.ac.in/admissions/

In [2]:
import requests
from bs4 import BeautifulSoup

In [3]:
url = "https://sece.ac.in/admissions/"

response = requests.get(url)

print(response.status_code)

200

In [4]:
print(response.text[:1000])

<!DOCTYPE html>
<html lang="en-US">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="profile" href="https://gmpg.org/xfn/11">
	<meta name='robots' content='index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1' />

		<script>try{if(!document.documentElement.classList.contains('sdui-panel-open')&&localStorage.getItem('site-designer-ui-panel-open')==='true'){document.documentElement.classList.add('sdui-panel-open');document.cookie='sdui_panel_open=1;path=/;max-age=31536000;SameSite=Lax;Secure';document.addEventListener('DOMContentLoaded',function(){if(!document.getElementById('sdui-panel-placeholder')){var p=document.createElement('div');p.id='sdui-panel-placeholder';document.body.appendChild(p)}})}}catch(e){}</script>

	<!-- This site is optimized with the Yoast SEO plugin v27.7 - https://yoast.com/product/yoast-seo-wordpress/ -->
	<title>Admissions - Sri Eshwar Engineering College</title>
	<meta n

In [5]:
soup = BeautifulSoup(response.text, "html.parser")

In [6]:
text = soup.get_text()

print(text[:5000])

Admissions - Sri Eshwar Engineering College




























































		Skip to content


Sri Eshwar Engineering College
















International Internship 2026 @ SECE












Campus tour










Admission 2025







 TNEA CODE2739

























Study In India
Alumni
ERP
Careers
IQAC
NBA DCP
Audited Statements
SDG CELL
Quick Links

Research Ethics Committee Examination Committee Grievance Redressal Committee (GRC) Library Advisory Committee Internal Complaints Committee (ICC) Counsellor Committee (CC) Anti Ragging Committee (ARC)  SC/ST Cell AICTE Feedback Contact

X




















HOME
ABOUT

Governance Leadership Vision & Mission Milestones Awards & Achievements

ACADEMICS

Academics @ Sri Eshwar Programmes Academic Calendar Departments

Computer Science Engineering (Artificial Intelligence & Machine Learning) Artificial Intelligence & Data Science (AI&DS) Computer Science and Engineering (CSE) Computer Science Engineering  (Cyber Security) Computer Science & Business Systems (CSBS) Computer & Communication Engineering (CCE) Electronics & Communication Engineering (ECE) Electronics Engineering (VLSI Design and Technology) Electrical & Electronics Engineering (EEE) Information Technology (IT) Mechanical Engineering (MECH) Science & Humanities (S&H)
Office of the COE Student Awards

RESEARCH

Centre for Research Academic Research

Research Publications Intellectual Property Rights (IPR) Research Institute
Sponsored Research

Research Grants Seed Funds

Slot Gacor
Consultancy Projects
Advanced Research Centres Research Facilities Research Conferences Downloads

INNOVATION

Centre for Innovation Centres of Excellence Institution Innovation Council (IIC) Hackathons Product Development Ignite Startup Accelerator Entrepreneurship Skill Development Downloads

INTERNATIONAL RELATIONS

Centre for International Relations Global Alliances Inward Mobility

Semester @ Sri Eshwar Internships @ Sri Eshwar Sri Eshwar Summer/Winter School Program
Outward Mobility

Semester Abroad Program International Internships Summer/Winter School Program

Things to do in Tokyo Plan a Trip to Tokyo Osaka Travel Guide

International Visiting Faculty International Internship 2026 @ SECE

CAREER DEVELOPMENT

Centre for Training & Placements Top Recruiters Placement Statistics Placement Training Programs Industry Institution Interaction Centre for Higher Education & Foreign Language

CAMPUS LIFE

Life @ Sri Eshwar Student Leadership Council Flagship Events Fine Arts Sports Clubs NCC Community Outreach Student Welfare Library Amenity Centre Medical Centre Hostel Transport

ADMISSIONS
X
















HOME
ABOUT

Governance Leadership Vision & Mission Milestones Awards & Achievements

ACADEMICS

Academics @ Sri Eshwar Programmes Academic Calendar Departments

Computer Science Engineering (Artificial Intelligence & Machine Learning) Artificial Intelligence & Data Science (AI&DS) Computer Science and Engineering (CSE) Computer Science Engineering  (Cyber Security) Computer Science & Business Systems (CSBS) Computer & Communication Engineering (CCE) Electronics & Communication Engineering (ECE) Electronics Engineering (VLSI Design and Technology) Electrical & Electronics Engineering (EEE) Information Technology (IT) Mechanical Engineering (MECH) Science & Humanities (S&H)
Office of the COE Student Awards

RESEARCH

Centre for Research Academic Research

Research Publications Intellectual Property Rights (IPR) Research Institute
Sponsored Research

Research Grants Seed Funds

Slot Gacor
Consultancy Projects
Advanced Research Centres Research Facilities Research Conferences Downloads

INNOVATION

Centre for Innovation Centres of Excellence Institution Innovation Council (IIC) Hackathons Product Development Ignite Startup Accelerator Entrepreneurship Skill Development Downloads

INTERNATIONAL RELATIONS

Centre for International Relations Global Alliances Inward Mobility

Semester @ Sri Eshwar Internships @ Sri Eshwar Sri Eshwar Summer/Winter School Program
Outward Mobility

Semester Abroad Program International Internships Summer/Winter School Program

Things to do in Tokyo Plan a Trip to Tokyo Osaka Travel Guide

International Visiting Faculty International Internship 2026 @ SECE

CAREER DEVELOPMENT

Centre for Training & Placements Top Recruiters Placement Statistics Placement Training Programs Industry Institution Interaction Centre for Higher Education & Foreign Language

CAMPUS LIFE

Life @ Sri Eshwar Student Leadership Council Flagship Events Fine Arts Sports Clubs NCC Community Outreach Student Welfare Library Amenity Centre Medical Centre Hostel Transport

ADMISSIONS
X











HOME
ABOUT

Governance Leadership Vision & Mission Milestones Awards & Achievements

ACADEMICS

Academics @ Sri Eshwar Programmes Academic Calendar Departments

Computer Science Engineering (Artificial Intelligence & Machine Learning) Artificial Intelligence & Data Sci

In [7]:
clean_text = " ".join(text.split())

print(clean_text[:3000])

Admissions - Sri Eshwar Engineering College Skip to content Sri Eshwar Engineering College International Internship 2026 @ SECE Campus tour Admission 2025 TNEA CODE2739 Study In India Alumni ERP Careers IQAC NBA DCP Audited Statements SDG CELL Quick Links Research Ethics Committee Examination Committee Grievance Redressal Committee (GRC) Library Advisory Committee Internal Complaints Committee (ICC) Counsellor Committee (CC) Anti Ragging Committee (ARC) SC/ST Cell AICTE Feedback Contact X HOME ABOUT Governance Leadership Vision & Mission Milestones Awards & Achievements ACADEMICS Academics @ Sri Eshwar Programmes Academic Calendar Departments Computer Science Engineering (Artificial Intelligence & Machine Learning) Artificial Intelligence & Data Science (AI&DS) Computer Science and Engineering (CSE) Computer Science Engineering (Cyber Security) Computer Science & Business Systems (CSBS) Computer & Communication Engineering (CCE) Electronics & Communication Engineering (ECE) Electronics Engineering (VLSI Design and Technology) Electrical & Electronics Engineering (EEE) Information Technology (IT) Mechanical Engineering (MECH) Science & Humanities (S&H) Office of the COE Student Awards RESEARCH Centre for Research Academic Research Research Publications Intellectual Property Rights (IPR) Research Institute Sponsored Research Research Grants Seed Funds Slot Gacor Consultancy Projects Advanced Research Centres Research Facilities Research Conferences Downloads INNOVATION Centre for Innovation Centres of Excellence Institution Innovation Council (IIC) Hackathons Product Development Ignite Startup Accelerator Entrepreneurship Skill Development Downloads INTERNATIONAL RELATIONS Centre for International Relations Global Alliances Inward Mobility Semester @ Sri Eshwar Internships @ Sri Eshwar Sri Eshwar Summer/Winter School Program Outward Mobility Semester Abroad Program International Internships Summer/Winter School Program Things to do in Tokyo Plan a Trip to Tokyo Osaka Travel Guide International Visiting Faculty International Internship 2026 @ SECE CAREER DEVELOPMENT Centre for Training & Placements Top Recruiters Placement Statistics Placement Training Programs Industry Institution Interaction Centre for Higher Education & Foreign Language CAMPUS LIFE Life @ Sri Eshwar Student Leadership Council Flagship Events Fine Arts Sports Clubs NCC Community Outreach Student Welfare Library Amenity Centre Medical Centre Hostel Transport ADMISSIONS X HOME ABOUT Governance Leadership Vision & Mission Milestones Awards & Achievements ACADEMICS Academics @ Sri Eshwar Programmes Academic Calendar Departments Computer Science Engineering (Artificial Intelligence & Machine Learning) Artificial Intelligence & Data Science (AI&DS) Computer Science and Engineering (CSE) Computer Science Engineering (Cyber Security) Computer Science & Business Systems (CSBS) Computer & Communication Engineering (CCE) Electronics & Communication Engineering (ECE) Electronics Engineering (

In [8]:
with open("sece_admissions.txt", "w", encoding="utf-8") as f:
    f.write(clean_text)

print("Saved Successfully")

Saved Successfully

In [9]:
import requests
from bs4 import BeautifulSoup

url = "https://sece.ac.in/"

response = requests.get(url)

soup = BeautifulSoup(response.text, "html.parser")

links = []

for a in soup.find_all("a", href=True):
    href = a["href"]

    if "sece.ac.in" in href:
        links.append(href)

links = list(set(links))

print("Number of links found:", len(links))

for link in links[:20]:
    print(link)

Number of links found: 83
https://sece.ac.in/plan-a-trip-to-tokyo/
https://sece.ac.in/consultancy-projects/
https://sece.ac.in/global-alliances/
https://sece.ac.in/achievements/
https://sece.ac.in/department-aids/
https://sece.ac.in/governance/
https://sece.ac.in/recruiters/
https://sece.ac.in/sdg/
https://sece.ac.in/events/
https://sece.ac.in/counsellor-committee/
https://sece.ac.in/contact-us/
https://sece.ac.in/student-awards/
https://sece.ac.in/academics/
https://sece.ac.in/department-mech/
https://sece.ac.in/feature-of-day/
https://sece.ac.in/departments/
https://sece.ac.in/admissions/
https://sece.ac.in/international-summer-internship-2026/
https://sece.ac.in/internal-complaints-committee/
https://sece.ac.in/department-computer-communication-engineering/

In [32]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

urls = [
    "https://sece.ac.in/admissions/",
    "https://sece.ac.in/academics/",
    "https://sece.ac.in/departments/",
    "https://sece.ac.in/recruiters/",
    "https://sece.ac.in/global-alliances/",
    "https://sece.ac.in/governance/",

    "https://sece.ac.in/department-mech/",
    "https://sece.ac.in/department-aids/",
    "https://sece.ac.in/department-computer-communication-engineering/"
]

data = []

for url in urls:
    try:
        response = requests.get(url)

        soup = BeautifulSoup(response.text, "html.parser")

        title = soup.title.text if soup.title else "No Title"

        text = soup.get_text(separator=" ", strip=True)

        clean_text = " ".join(text.split())

        data.append({
            "url": url,
            "title": title,
            "text": clean_text
        })

        print(f"Done: {url}")

    except Exception as e:
        print(f"Error: {url}")
        print(e)

df = pd.DataFrame(data)

df.head()

Done: https://sece.ac.in/admissions/
Done: https://sece.ac.in/academics/
Done: https://sece.ac.in/departments/
Done: https://sece.ac.in/recruiters/
Done: https://sece.ac.in/global-alliances/
Done: https://sece.ac.in/governance/
Done: https://sece.ac.in/department-mech/
Done: https://sece.ac.in/department-aids/
Done: https://sece.ac.in/department-computer-communication-engineering/

,url,title,text
0,https://sece.ac.in/admissions/,Admissions - Sri Eshwar Engineering College,Admissions - Sri Eshwar Engineering College Sk...
1,https://sece.ac.in/academics/,Academics - Sri Eshwar Engineering College,Academics - Sri Eshwar Engineering College Ski...
2,https://sece.ac.in/departments/,All Departments - Sri Eshwar Engineering College,All Departments - Sri Eshwar Engineering Colle...
3,https://sece.ac.in/recruiters/,Recruiters - Sri Eshwar Engineering College,Recruiters - Sri Eshwar Engineering College Sk...
4,https://sece.ac.in/global-alliances/,global-alliances - Sri Eshwar Engineering College,global-alliances - Sri Eshwar Engineering Coll...

In [11]:
df.to_csv("sece_knowledge_base.csv", index=False)

print("CSV saved successfully!")

CSV saved successfully!

In [12]:
df.shape

(7, 3)

In [13]:
import pandas as pd

df = pd.read_csv("sece_knowledge_base.csv")

chunks = []

chunk_size = 500

for _, row in df.iterrows():

    text = row["text"]

    for i in range(0, len(text), chunk_size):

        chunk = text[i:i+chunk_size]

        chunks.append({
            "source_url": row["url"],
            "title": row["title"],
            "chunk_text": chunk
        })

chunk_df = pd.DataFrame(chunks)

print("Total Chunks:", len(chunk_df))

chunk_df.head()

Total Chunks: 359

,source_url,title,chunk_text
0,https://sece.ac.in/admissions/,Admissions - Sri Eshwar Engineering College,Admissions - Sri Eshwar Engineering College Sk...
1,https://sece.ac.in/admissions/,Admissions - Sri Eshwar Engineering College,ABOUT Governance Leadership Vision & Mission M...
2,https://sece.ac.in/admissions/,Admissions - Sri Eshwar Engineering College,s Engineering (VLSI Design and Technology) Ele...
3,https://sece.ac.in/admissions/,Admissions - Sri Eshwar Engineering College,for Innovation Centres of Excellence Instituti...
4,https://sece.ac.in/admissions/,Admissions - Sri Eshwar Engineering College,Travel Guide International Visiting Faculty I...

In [14]:
chunk_df.to_csv("sece_chunks.csv", index=False)

print("Chunks saved!")

Chunks saved!

In [15]:
chunk_df.shape

(359, 3)

In [36]:
!pip install sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.5.1)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.9.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.17.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.11.0+cpu)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.25.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (0.1.2)

In [37]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2"
)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [18]:
texts = chunk_df["chunk_text"].tolist()

embeddings = model.encode(
    texts,
    show_progress_bar=True
)

print(embeddings.shape)

Batches:   0%|          | 0/12 [00:00<?, ?it/s]

(359, 384)

In [19]:
chunk_df.shape

(359, 3)

In [20]:
!pip install faiss-cpu

Collecting faiss-cpu
  Downloading faiss_cpu-1.14.2-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (7.8 kB)
Requirement already satisfied: numpy>=1.25 in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (26.2)
Downloading faiss_cpu-1.14.2-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (18.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 48.7 MB/s eta 0:00:00
Installing collected packages: faiss-cpu
Successfully installed faiss-cpu-1.14.2

In [21]:
import faiss
import numpy as np

embedding_array = np.array(
    embeddings,
    dtype="float32"
)

dimension = embedding_array.shape[1]

index = faiss.IndexFlatL2(dimension)

index.add(embedding_array)

print("Vectors stored:", index.ntotal)

Vectors stored: 359

In [22]:
query = "placement opportunities"

query_embedding = model.encode([query])

D, I = index.search(
    np.array(query_embedding, dtype="float32"),
    k=5
)

print(I)

[[ 27  20 129 323 297]]

In [23]:
for idx in I[0]:
    print("=" * 80)
    print(chunk_df.iloc[idx]["chunk_text"])

================================================================================
ge and finding solutions to problems together. Excellent Placement Opportunities With over 150+ top companies visiting our campus all year round for placements, it is sure that you will be placed in the company of your choice and be placed in the range of 4L to 40L per annum. All we need from you is your hard work and a great attitude. We will do the rest! Excellent Research opportunities If you are interested in diving deep into academics and pursuing research, Sri Eshwar is the right place for
================================================================================
ty CAREER DEVELOPMENT Centre for Training & Placements Top Recruiters Placement Statistics Placement Training Programs Industry Institution Interaction Centre for Higher Education & Foreign Language CAMPUS LIFE Life @ Sri Eshwar Flagship Events Student Leadership Council Fine Arts Sports Clubs NCC Community Outreach Student Welfare Library Amenity Centre Medical Centre Hostel Transport ADMISSIONS ERP IQAC ALUMNI CAREER QUICK LINKS Grievance Redressal Committee Anti Ragging Committee Student Welf
================================================================================
ty CAREER DEVELOPMENT Centre for Training & Placements Top Recruiters Placement Statistics Placement Training Programs Industry Institution Interaction Centre for Higher Education & Foreign Language CAMPUS LIFE Life @ Sri Eshwar Flagship Events Student Leadership Council Fine Arts Sports Clubs NCC Community Outreach Student Welfare Library Amenity Centre Medical Centre Hostel Transport ADMISSIONS ERP IQAC ALUMNI CAREER QUICK LINKS Grievance Redressal Committee Anti Ragging Committee Student Welf
================================================================================
ty CAREER DEVELOPMENT Centre for Training & Placements Top Recruiters Placement Statistics Placement Training Programs Industry Institution Interaction Centre for Higher Education & Foreign Language CAMPUS LIFE Life @ Sri Eshwar Flagship Events Student Leadership Council Fine Arts Sports Clubs NCC Community Outreach Student Welfare Library Amenity Centre Medical Centre Hostel Transport ADMISSIONS ERP IQAC ALUMNI CAREER QUICK LINKS Grievance Redressal Committee Anti Ragging Committee Student Welf
================================================================================
 Faculty CAREER DEVELOPMENT Centre for Training & Placements Top Recruiters Placement Statistics Placement Training Programs Industry Institution Interaction Centre for Higher Education & Foreign Language CAMPUS LIFE Life @ Sri Eshwar Flagship Events Student Leadership Council Fine Arts Sports Clubs NCC Community Outreach Student Welfare Library Amenity Centre Medical Centre Hostel Transport ADMISSIONS ERP IQAC ALUMNI CAREER QUICK LINKS Grievance Redressal Committee Anti Ragging Committee Studen

In [27]:
import numpy as np

def search_chunks(query, k=5):

    print(f"\n{'#'*100}")
    print(f"QUERY: {query}")
    print(f"{'#'*100}")

    query_embedding = model.encode([query])

    D, I = index.search(
        np.array(query_embedding, dtype="float32"),
        k=k
    )

    for rank, idx in enumerate(I[0], start=1):

        print(f"\n{'='*100}")
        print(f"Result {rank}")
        print(f"Chunk Index: {idx}")

        print("\nSource URL:")
        print(chunk_df.iloc[idx]["source_url"])

        print("\nTitle:")
        print(chunk_df.iloc[idx]["title"])

        print("\nChunk Text:")
        print(chunk_df.iloc[idx]["chunk_text"][:1000])  # show first 1000 chars


# Test Query 1
search_chunks("admission process")

# Test Query 2
search_chunks("mechanical engineering department")

# Test Query 3
search_chunks("international collaboration")

####################################################################################################
QUERY: admission process
####################################################################################################

====================================================================================================
Result 1
Chunk Index: 39

Source URL:
https://sece.ac.in/admissions/

Title:
Admissions - Sri Eshwar Engineering College

Chunk Text:
ubjects in the qualifying degree alone will generally be considered for admissions. The candidates have to indicate their order of Preference of Branches of study in the application. Mode of selection - Selection Committee will scrutinize the applications received based on eligibility criteria and intimate the applicants. Required Documents Candidates who are admitted under this scheme must obtain valid student visa issued by Indian missions abroad. Passport of the candidate. Valid student Visa

====================================================================================================
Result 2
Chunk Index: 329

Source URL:
https://sece.ac.in/governance/

Title:
Governance - Sri Eshwar Engineering College

Chunk Text:
d we are hugely successful in placements. Today we stand across Tamil Nadu as a top placements college. Every day at Sri Eshwar, every hour, every minute, every second – we stand unified with the goal of how to make students successful. Our team works very hard, with a smile on our face, towards this common vision to bring Sri Eshwar to the pinnacle of success. Our students’ success is our success. COME JOIN US TO EXPERIENCE LEARNING AT ITS BEST! ADMISSIONS Linkedin Youtube Instagram X-twitter P

====================================================================================================
Result 3
Chunk Index: 0

Source URL:
https://sece.ac.in/admissions/

Title:
Admissions - Sri Eshwar Engineering College

Chunk Text:
Admissions - Sri Eshwar Engineering College Skip to content Sri Eshwar Engineering College International Internship 2026 @ SECE Campus tour Admission 2025 TNEA CODE 2739 Study In India Alumni ERP Careers IQAC NBA DCP Audited Statements SDG CELL Quick Links Research Ethics Committee Examination Committee Grievance Redressal Committee (GRC) Library Advisory Committee Internal Complaints Committee (ICC) Counsellor Committee (CC) Anti Ragging Committee (ARC) SC/ST Cell AICTE Feedback Contact X HOME

====================================================================================================
Result 4
Chunk Index: 36

Source URL:
https://sece.ac.in/admissions/

Title:
Admissions - Sri Eshwar Engineering College

Chunk Text:
 qualifying examination. Candidate should have studied in English Medium or English as one of the subjects in the qualifying Examination. Candidates must have passed the qualifying examination, i.e. (10 + 2) of Indian System or its equivalent (completed 12 years of school education). The Candidate should have passed in all the subjects and scored a minimum average of 45 percentage in Mathematics, Physics and Chemistry. If the candidate has grade certificates, he/she has to produce either the act

====================================================================================================
Result 5
Chunk Index: 105

Source URL:
https://sece.ac.in/departments/

Title:
All Departments - Sri Eshwar Engineering College

Chunk Text:
 Artificial intelligence and Data Science (AI&DS) Computer Science and Business Systems (CS&BS) Information Technology (IT) Science & Humanities COME JOIN US TO EXPERIENCE LEARNING AT ITS BEST! ADMISSIONS Linkedin Youtube Instagram X-twitter PROGRAMMES UG Programmes PG Programmes Doctorate Programmes MAIN LINKS About Us Academics Research Innovation International Relations Career Development Campus Life Admissions Contact QUICK LINKS Anti-Ragging Cell Grievance Redressal Internal Complaints Coun

####################################################################################################
QUERY: mechanical engineering department
####################################################################################################

====================================================================================================
Result 1
Chunk Index: 173

Source URL:
https://sece.ac.in/recruiters/

Title:
Recruiters - Sri Eshwar Engineering College

Chunk Text:
ical 2022 On Campus Virtusa 35 Naveenkumar A 722818114044 Mechanical 2022 On Campus BCT 36 Naveen Siddharth S 722818114045 Mechanical 2022 On Campus Integra Automation 37 Navith Apzal M 722818114046 Mechanical 2022 On Campus Chainsys 38 Praveen S 722818114047 Mechanical 2022 On Campus Pinnacle Infotech 39 Praveenchanthru S 722818114048 Mechanical 2022 On Campus Caresoft 40 Ragu M 722818114049 Mechanical 2022 On Campus Flowserve 41 Rakesh S K 722818114050 Mechanical 2022 On Campus BCT 42 Ramesh K

====================================================================================================
Result 2
Chunk Index: 177

Source URL:
https://sece.ac.in/recruiters/

Title:
Recruiters - Sri Eshwar Engineering College

Chunk Text:
shanth M 722818114080 Mechanical 2022 On Campus Schuf 66 Koushick R 722818114312 Mechanical 2022 On Campus Tata Technologies 67 Ragul Raj R 722818114313 Mechanical 2022 On Campus AVTEC 68 Selvayukesh M 722818114317 Mechanical 2022 On Campus Caresoft 69 Sivamurugan B 722818114318 Mechanical 2022 On Campus Integra Automation 70 Sridhar S 722818114319 Mechanical 2022 On Campus Caresoft 71 Vimal Krishnan K N 722818114321 Mechanical 2022 On Campus Axis Cades AIDS CSE ECE EEE CCE IT MECH S NO NAME REG

====================================================================================================
Result 3
Chunk Index: 174

Source URL:
https://sece.ac.in/recruiters/

Title:
Recruiters - Sri Eshwar Engineering College

Chunk Text:
rishnaa S L 722818114051 Mechanical 2022 On Campus CTS 43 Sabari Sridaran G 722818114054 Mechanical 2022 On Campus Apexon 44 Sandhiya S 722818114056 Mechanical 2022 On Campus Flowserve 45 Sanjay V C 722818114057 Mechanical 2022 On Campus Vivriti Capital 46 Saptha Giri 722818114059 Mechanical 2022 On Campus BCT 47 Sarathchandran M 722818114060 Mechanical 2022 On Campus DXC 48 Saurav Rishikesh S 722818114061 Mechanical 2022 On Campus Gyanmatrix 49 Seenivasan N 722818114062 Mechanical 2022 On Campu

====================================================================================================
Result 4
Chunk Index: 223

Source URL:
https://sece.ac.in/recruiters/

Title:
Recruiters - Sri Eshwar Engineering College

Chunk Text:
 / Off Campus Name of the Employer 1 Abhishek Singh 722819114001 Mechanical 2023 On Campus Tekizma 2 Alagu Vignesh K 722819114002 Mechanical 2023 On Campus Aaress Exports 3 Anijith Raghuvance T 722819114003 Mechanical 2023 On Campus Schwing Stetter 4 Aswanth S 722819114005 Mechanical 2023 On Campus Focus R 5 Dhanush Darshan S A 722819114009 Mechanical 2023 On Campus Vivait 6 Dharanidharan M 722819114010 Mechanical 2023 On Campus Caresoft Global 7 Dinesh Gowtham K 722819114011 Mechanical 2023 On

====================================================================================================
Result 5
Chunk Index: 172

Source URL:
https://sece.ac.in/recruiters/

Title:
Recruiters - Sri Eshwar Engineering College

Chunk Text:
722818114041 Mechanical 2022 On Campus Bimetal Bearing 28 Athesh N 722818114301 Mechanical 2022 On Campus KGISL Microwave 29 Barathvaaj D 722818114302 Mechanical 2022 On Campus Gyanmatrix 30 Dhanush S 722818114306 Mechanical 2022 On Campus Candor Commitment Delivered 31 Gowtham A 722818114307 Mechanical 2022 On Campus DXC 32 Hari Harasudhan S 722818114308 Mechanical 2022 On Campus K Tech Solution 33 Jayasuriya K 722818114310 Mechanical 2022 On Campus Severn Glocon 34 Karthi M 722818114311 Mechan

####################################################################################################
QUERY: international collaboration
####################################################################################################

====================================================================================================
Result 1
Chunk Index: 19

Source URL:
https://sece.ac.in/admissions/

Title:
Admissions - Sri Eshwar Engineering College

Chunk Text:
PR) Research Institute Sponsored Research Research Grants Seed Funds Consultancy Projects Advanced Research Centres Research Facilities Research Conferences Downloads INNOVATION Centre for Innovation Centres of Excellence Institution Innovation Council (IIC) Hackthons Product Development IGNITE – Startup Accelerator Entrepreneurship Skill Development Downloads INTERNATIONAL RELATIONS Centre for International Relations global-alliances Inward Mobility Outward Mobility International Visiting Facul

====================================================================================================
Result 2
Chunk Index: 128

Source URL:
https://sece.ac.in/recruiters/

Title:
Recruiters - Sri Eshwar Engineering College

Chunk Text:
PR) Research Institute Sponsored Research Research Grants Seed Funds Consultancy Projects Advanced Research Centres Research Facilities Research Conferences Downloads INNOVATION Centre for Innovation Centres of Excellence Institution Innovation Council (IIC) Hackthons Product Development IGNITE – Startup Accelerator Entrepreneurship Skill Development Downloads INTERNATIONAL RELATIONS Centre for International Relations global-alliances Inward Mobility Outward Mobility International Visiting Facul

====================================================================================================
Result 3
Chunk Index: 322

Source URL:
https://sece.ac.in/governance/

Title:
Governance - Sri Eshwar Engineering College

Chunk Text:
PR) Research Institute Sponsored Research Research Grants Seed Funds Consultancy Projects Advanced Research Centres Research Facilities Research Conferences Downloads INNOVATION Centre for Innovation Centres of Excellence Institution Innovation Council (IIC) Hackthons Product Development IGNITE – Startup Accelerator Entrepreneurship Skill Development Downloads INTERNATIONAL RELATIONS Centre for International Relations global-alliances Inward Mobility Outward Mobility International Visiting Facul

====================================================================================================
Result 4
Chunk Index: 65

Source URL:
https://sece.ac.in/academics/

Title:
Academics - Sri Eshwar Engineering College

Chunk Text:
R) Research Institute Sponsored Research Research Grants Seed Funds Consultancy Projects Advanced Research Centres Research Facilities Research Conferences Downloads INNOVATION Centre for Innovation Centres of Excellence Institution Innovation Council (IIC) Hackthons Product Development IGNITE – Startup Accelerator Entrepreneurship Skill Development Downloads INTERNATIONAL RELATIONS Centre for International Relations global-alliances Inward Mobility Outward Mobility International Visiting Facult

====================================================================================================
Result 5
Chunk Index: 353

Source URL:
https://sece.ac.in/contact-us/

Title:
Page not found - Sri Eshwar Engineering College

Chunk Text:
s (IPR) Research Institute Sponsored Research Research Grants Seed Funds Consultancy Projects Advanced Research Centres Research Facilities Research Conferences Downloads INNOVATION Centre for Innovation Centres of Excellence Institution Innovation Council (IIC) Hackthons Product Development IGNITE – Startup Accelerator Entrepreneurship Skill Development Downloads INTERNATIONAL RELATIONS Centre for International Relations global-alliances Inward Mobility Outward Mobility International Visiting F

In [28]:
urls = chunk_df["source_url"].unique()

for url in urls:
    print(url)

https://sece.ac.in/admissions/
https://sece.ac.in/academics/
https://sece.ac.in/departments/
https://sece.ac.in/recruiters/
https://sece.ac.in/global-alliances/
https://sece.ac.in/governance/
https://sece.ac.in/contact-us/

In [33]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

data = []

for url in urls:

    try:

        response = requests.get(url)

        soup = BeautifulSoup(response.text, "html.parser")

        title = soup.title.text if soup.title else "No Title"

        text = soup.get_text(separator=" ", strip=True)

        clean_text = " ".join(text.split())

        data.append({
            "url": url,
            "title": title,
            "text": clean_text
        })

        print("Done:", url)

    except Exception as e:

        print("Error:", url)
        print(e)

df = pd.DataFrame(data)

print(df.shape)
df.head()

Done: https://sece.ac.in/admissions/
Done: https://sece.ac.in/academics/
Done: https://sece.ac.in/departments/
Done: https://sece.ac.in/recruiters/
Done: https://sece.ac.in/global-alliances/
Done: https://sece.ac.in/governance/
Done: https://sece.ac.in/department-mech/
Done: https://sece.ac.in/department-aids/
Done: https://sece.ac.in/department-computer-communication-engineering/
(9, 3)

,url,title,text
0,https://sece.ac.in/admissions/,Admissions - Sri Eshwar Engineering College,Admissions - Sri Eshwar Engineering College Sk...
1,https://sece.ac.in/academics/,Academics - Sri Eshwar Engineering College,Academics - Sri Eshwar Engineering College Ski...
2,https://sece.ac.in/departments/,All Departments - Sri Eshwar Engineering College,All Departments - Sri Eshwar Engineering Colle...
3,https://sece.ac.in/recruiters/,Recruiters - Sri Eshwar Engineering College,Recruiters - Sri Eshwar Engineering College Sk...
4,https://sece.ac.in/global-alliances/,global-alliances - Sri Eshwar Engineering College,global-alliances - Sri Eshwar Engineering Coll...

In [34]:
def chunk_text(text, chunk_size=100):

    words = text.split()

    chunks = []

    for i in range(0, len(words), chunk_size):

        chunk = " ".join(words[i:i + chunk_size])

        chunks.append(chunk)

    return chunks

In [35]:
chunks = []

for _, row in df.iterrows():

    page_chunks = chunk_text(
        row["text"],
        chunk_size=100
    )

    for chunk in page_chunks:

        chunks.append({
            "source_url": row["url"],
            "title": row["title"],
            "chunk_text": chunk
        })

import pandas as pd

chunk_df = pd.DataFrame(chunks)

print(chunk_df.shape)

chunk_df.head()

(438, 3)

,source_url,title,chunk_text
0,https://sece.ac.in/admissions/,Admissions - Sri Eshwar Engineering College,Admissions - Sri Eshwar Engineering College Sk...
1,https://sece.ac.in/admissions/,Admissions - Sri Eshwar Engineering College,Data Science (AI&DS) Computer Science and Engi...
2,https://sece.ac.in/admissions/,Admissions - Sri Eshwar Engineering College,Product Development Ignite Startup Accelerator...
3,https://sece.ac.in/admissions/,Admissions - Sri Eshwar Engineering College,Sports Clubs NCC Community Outreach Student We...
4,https://sece.ac.in/admissions/,Admissions - Sri Eshwar Engineering College,COE Student Awards RESEARCH Centre for Researc...

In [38]:
texts = chunk_df["chunk_text"].tolist()

embeddings = model.encode(
    texts,
    show_progress_bar=True
)

print(embeddings.shape)

Batches:   0%|          | 0/14 [00:00<?, ?it/s]

(438, 384)

In [39]:
!pip install faiss-cpu

Requirement already satisfied: faiss-cpu in /usr/local/lib/python3.12/dist-packages (1.14.2)
Requirement already satisfied: numpy>=1.25 in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (26.2)

In [40]:
import faiss
import numpy as np

embedding_array = np.array(
    embeddings,
    dtype="float32"
)

dimension = embedding_array.shape[1]

index = faiss.IndexFlatL2(dimension)

index.add(embedding_array)

print("Vectors stored:", index.ntotal)

Vectors stored: 438

In [55]:
def search_chunks(query, k=5):

    query_embedding = model.encode([query])

    D, I = index.search(
        np.array(query_embedding, dtype="float32"),
        k=k
    )

    results = []

    for idx in I[0]:
        results.append({
            "text": chunk_df.iloc[idx]["chunk_text"],
            "url": chunk_df.iloc[idx]["source_url"]
        })

    return results

In [56]:
results = search_chunks(
    "What are the admission requirements?"
)

for r in results:
    print("\n" + "="*80)
    print(r)

================================================================================
{'text': '- MECH 184 182 - 175.5 147 - - Cyber Security 190.5 189 186 185 159 150.5 - UG Lateral Admissions If you have completed your Diploma or B.Sc and looking to join as a Lateral Entry student in the IInd year (3rd Semester), here are the entry requirements. Eligibility Pass in Diploma/B.Sc degree exam OC 45% BC Including BC Muslim 45% MBC and DNC 40% SC/SCA/ST 40% foreign nationals - ADMISSION PROCEDURE Admissions BE / BTech Programmes and under Foreign Nationals Overseas Citizen of India (OCI). Who can Apply? Foreign National(FN) - “Foreign National” means the Citizen of the', 'url': 'https://sece.ac.in/admissions/'}

================================================================================
{'text': 'keep students happy and relaxed. indian citizens - admission procedure BE / BTech If you have just finished your 12th Grade, here are the entry Requirements for B.E, B.Tech Programs through Single Window Counselling. Pass in +12 examinations with Minimum Avg marks in Mathematics, Physics, Chemistry as follows. OC 45% BC Including BC Muslim 40% MBC and DNC 40% SC/SCA/ST 40% For students who have completed Higher Secondary Course (Other than CBSE/Tamil Nadu Board), an equivalency certificate obtained from the Association of Indian Universities (AIU), New Delhi. In case of grading, lower bound of the mark ranges of a grade', 'url': 'https://sece.ac.in/admissions/'}

================================================================================
{'text': 'should be taken for calculating the percentage of marks. ADMISSIONS Mr.R.Rajaram Director +91 73736 17171 Email: director@sece.ac.in Linkedin Youtube Instagram X-twitter PROGRAMMES UG Programmes PG Programmes Doctorate Programmes MAIN LINKS About Us Academics Research Innovation International Relations Career Development Campus Life Admissions Contact QUICK LINKS Anti-Ragging Cell Grievance Redressal Internal Complaints Counsellor Committee SC/ST Cell SECE @ Media Mandatory Disclosure Security Audit AICTE Feedback Rules and Regulations Policies Contact AICTE Scholarship / Fellowship Schemes ACCREDITATIONS NBA NIRF CALL US +91-4259 200 300 LOCATION COIMBATORE EMAIL sece@sece.ac.in © 2024 Sri Eshwar Engineering College. All Rights Reserved. Admission Enquiry 2025 Please enable', 'url': 'https://sece.ac.in/admissions/'}

================================================================================
{'text': 'required for BE/BTech (Four Year) Degree programmes For admission to B.E./B.Tech Courses, candidates should have completed 12 years of schooling (equivalent to 10+2 system of Indian Education). They must have studied and obtained a pass with Good Grades as per their systems of education with Physics, Chemistry and Mathematics as their subjects in the qualifying examination. Candidate should have studied in English Medium or English as one of the subjects in the qualifying Examination. Candidates must have passed the qualifying examination, i.e. (10 + 2) of Indian System or its equivalent (completed 12 years of school education). The Candidate should', 'url': 'https://sece.ac.in/admissions/'}

================================================================================
{'text': 'admissions. The candidates have to indicate their order of Preference of Branches of study in the application. Mode of selection - Selection Committee will scrutinize the applications received based on eligibility criteria and intimate the applicants. Required Documents Candidates who are admitted under this scheme must obtain valid student visa issued by Indian missions abroad. Passport of the candidate. Valid student Visa / OCI card (In case of Citizen of Indian Origin). Proof of Financial support like parents bank statement for the last six months. School Transfer Certificate / Migration Certificate. If these certificates are not issued in the respective', 'url': 'https://sece.ac.in/admissions/'}

In [43]:
!pip install groq

Collecting groq
  Downloading groq-1.4.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from groq) (4.13.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from groq) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from groq) (0.28.1)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from groq) (2.12.3)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from groq) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.14 in /usr/local/lib/python3.12/dist-packages (from groq) (4.15.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->groq) (3.18)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->groq) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->groq) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->groq) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (0.4.2)
Downloading groq-1.4.0-py3-none-any.whl (143 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.7/143.7 kB 2.0 MB/s eta 0:00:00
Installing collected packages: groq
Successfully installed groq-1.4.0

groq api - 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

In [44]:
from groq import Groq

client = Groq(
    api_key="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"
)

In [57]:
def ask_sece(question):

    retrieved = search_chunks(question, k=5)

    context = "\n\n".join(
        [item["text"] for item in retrieved]
    )

    sources = list(set(
        [item["url"] for item in retrieved]
    ))

    prompt = f"""
You are the official SECE Information Assistant.

Answer ONLY from the provided context.

If the answer is not present in the context, reply exactly:

'I could not find that information in the SECE knowledge base.'

Context:
{context}

Question:
{question}

Answer:
"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0.2
    )

    answer = response.choices[0].message.content

    answer += "\n\nSources:\n"

    for source in sources:
        answer += f"- {source}\n"

    return answer

In [58]:
print(
    ask_sece(
        "What are the admission requirements?"
    )
)

For B.E/B.Tech admissions through Single Window Counselling, the requirements are:
- Pass in +12 examinations with Minimum Avg marks in Mathematics, Physics, Chemistry as follows:
  - OC: 45%
  - BC Including BC Muslim: 40%
  - MBC and DNC: 40%
  - SC/SCA/ST: 40%
For Lateral Entry admissions, the requirements are:
- Pass in Diploma/B.Sc degree exam with the following percentages:
  - OC: 45%
  - BC Including BC Muslim: 45%
  - MBC and DNC: 40%
  - SC/SCA/ST: 40%
For Foreign Nationals, the requirements include a valid student visa and other documents such as passport, proof of financial support, and school transfer certificate.

Sources:
- https://sece.ac.in/admissions/

In [59]:
print(
    ask_sece(
        "Tell me about Mechanical Engineering department"
    )
)

The Mechanical Engineering department at Sri Eshwar Engineering College has a vast and diverse scope, offering numerous opportunities for graduates to pursue rewarding careers in various industries. The department provides a solid foundation in engineering principles, including topics such as statics, dynamics, thermodynamics, fluid mechanics, manufacturing, and mechanical design. Students can design, analyse, and optimize mechanical systems and components using Computer-Aided Design (CAD), Finite Element Analysis (FEA), and Computational Fluid Dynamics (CFD). The department also covers other important areas such as additive manufacturing (3D printing), quality control, process optimization, robotic and industrial automation, control systems, mechatronics, renewable energy systems, and HVAC. The vision of the department is to become an integrated center of excellence focusing on design, manufacturing, and industrial engineering, providing societal benefits through academic services including research and innovation.

Sources:
- https://sece.ac.in/department-mech/

In [60]:
!pip install gradio

Requirement already satisfied: gradio in /usr/local/lib/python3.12/dist-packages (5.50.0)
Requirement already satisfied: aiofiles<25.0,>=22.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (24.1.0)
Requirement already satisfied: anyio<5.0,>=3.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (4.13.0)
Requirement already satisfied: brotli>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (1.2.0)
Requirement already satisfied: fastapi<1.0,>=0.115.2 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.136.3)
Requirement already satisfied: ffmpy in /usr/local/lib/python3.12/dist-packages (from gradio) (1.0.0)
Requirement already satisfied: gradio-client==1.14.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (1.14.0)
Requirement already satisfied: groovy~=0.1 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.1.2)
Requirement already satisfied: httpx<1.0,>=0.24.1 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.28.1)
Requirement already satisfied: huggingface-hub<2.0,>=0.33.5 in /usr/local/lib/python3.12/dist-packages (from gradio) (1.17.0)
Requirement already satisfied: jinja2<4.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.1.6)
Requirement already satisfied: markupsafe<4.0,>=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.0.3)
Requirement already satisfied: numpy<3.0,>=1.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.0.2)
Requirement already satisfied: orjson~=3.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.11.9)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from gradio) (26.2)
Requirement already satisfied: pandas<3.0,>=1.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.2.2)
Requirement already satisfied: pillow<12.0,>=8.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (11.3.0)
Requirement already satisfied: pydantic<=2.12.3,>=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.12.3)
Requirement already satisfied: pydub in /usr/local/lib/python3.12/dist-packages (from gradio) (0.25.1)
Requirement already satisfied: python-multipart>=0.0.18 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.0.30)
Requirement already satisfied: pyyaml<7.0,>=5.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (6.0.3)
Requirement already satisfied: ruff>=0.9.3 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.15.15)
Requirement already satisfied: safehttpx<0.2.0,>=0.1.6 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.1.7)
Requirement already satisfied: semantic-version~=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.10.0)
Requirement already satisfied: starlette<1.0,>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.52.1)
Requirement already satisfied: tomlkit<0.14.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.13.3)
Requirement already satisfied: typer<1.0,>=0.12 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.25.1)
Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (4.15.0)
Requirement already satisfied: uvicorn>=0.14.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.48.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from gradio-client==1.14.0->gradio) (2025.3.0)
Requirement already satisfied: websockets<16.0,>=13.0 in /usr/local/lib/python3.12/dist-packages (from gradio-client==1.14.0->gradio) (15.0.1)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5.0,>=3.0->gradio) (3.18)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1.0,>=0.115.2->gradio) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1.0,>=0.115.2->gradio) (0.0.4)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0,>=0.24.1->gradio) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0,>=0.24.1->gradio) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0,>=0.24.1->gradio) (0.16.0)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (3.29.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (1.5.0)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (4.67.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=1.0->gradio) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=1.0->gradio) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=1.0->gradio) (2026.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<=2.12.3,>=2.0->gradio) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<=2.12.3,>=2.0->gradio) (2.41.4)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0,>=0.12->gradio) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0,>=0.12->gradio) (13.9.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3.0,>=1.0->gradio) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<1.0,>=0.12->gradio) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<1.0,>=0.12->gradio) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0,>=0.12->gradio) (0.1.2)

In [61]:
def chatbot(message, history):

    response = ask_sece(message)

    return response

In [62]:
import gradio as gr

demo = gr.ChatInterface(
    fn=chatbot,
    title="SECE RAG Assistant",
    description="Ask questions about Sri Eshwar Engineering College"
)

demo.launch(share=True)

/usr/local/lib/python3.12/dist-packages/gradio/chat_interface.py:347: UserWarning: The 'tuples' format for chatbot messages is deprecated and will be removed in a future version of Gradio. Please set type='messages' instead, which uses openai-style 'role' and 'content' keys.
  self.chatbot = Chatbot(

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://c4887bda9713c2a867.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)